language: java
script: echo Deploying
notifications:
  email:
    recipients:
    - alexander@district0x.io
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
services:
- docker
deploy:
- provider: script
  script: bash docker-push.sh
  on:
    branch: master
env:
  global:
  - secure: YFYSKJhoYDUYxacE7iEhPWIz8vIejFIMwP/SyGeJ+VWsUtk+wY9gLH5HbiRK/tI5QpF8gcmcmJI31aQNGDfzuShZxpS/WKlJSDRBjW7fk+KwFJQ8hKYa8mUuDCq8xZNJPe5gecI0qfFOv+ghlgqyfKcnVi93PKiSliAXuwqqocddP0qCt1QGsr/P3Wo6IMOUW8BTS65q/CtytTzMIF+ubJr1MgGC9hB7tnxQ+jZFMYN8BGKqkgBcdP0obQh7XuggagWadMI0cWyGgTzhBhr/GZiHuLyqOoQWuCNGUhDJjZ6bl35FpbwqYwMf193FNbeKY+KLzoQOHZwrXFcDt/7rzapxPmQfsGm5GudZe5VqzZuulbtC9BYVig7FQqFKs4deRbDMno5Dw9J733M9fvBnxjxq6DpZLcGylGG5VK1M4DpLSXuVvDJOdWRtOUdn6KRTjJGGbveOk2AcWOxOTS1CBlGW8J/dx0+i5Aq9sfB9cLAAAhRhXxHu8w1dqaETR4jyLBinrSdf966e5HfCCRA6U9Q6hPrDp57980owcStNoN3yYvBRNfKbPr8Efz01gBmYFzhwb0SaY8CZeg2hAnkJS7Gzwrj1TXSL52og/0YCqHokJ8+U4DtOlDObVl+NDVfWjFfkPAkjTh0Jgvu5Utb5tMyeJtNoN14jpneYw5VpfGA=
  - secure: cm/0V2NaEa6nyFFpBD69Sf1FY2Xa6cCDK4cbst4drzIfd0PNnX33+Mw5xo3zagWPZg6QsGxF/U+SvqzlpCju8D7S7pRasVqbxa7LT/HZZZELf27VxP2c0fAHTVi3akrvp65CojNB5DndOMMyilnu5SmHT+Fyf1I6l6VksZby/6YtWjTN6KnzsPDJB+1hEXi4Gwhndrcl8eP4Dqx9+NY+l2g38XKYuwK+mlGvmSEgtQZU7CB6LfwsK99aCw5lTaIelyV/O4KOVAUUsf+xPoL0ar+IPTpZIxCgfh3TCYzQFrDMrN2WXCY1p28ysd2ejekbKKfmvfUPuBUJ4ecm54qzKMx2+BLDcIOKdlm5XcsCXwpfjagCPeaL0lbl6ktp4YwMb42PROWl6w6xwnKT0Wq2d/HqDTJDmoaZdn2t71XUbIvnLBxN2Rq1aYSD4rii/9GUpffXt1/PITR9gOCA4jpe4DykByLp77UC+BOhBuo5bpRdpsUt2GCPX+3eSePRnxzkcMMsQmppYt6ZJjkEnsu2ui+N/r6GZNm99ziXRH4VV4NDqEaE3kZYFuYRZDQ1Xo8qrb8X2jtB+l/dXatndlgNkQvpbvq6vf8kadSodSoJvqnukOvgAzbwSnzepW/9YQlw2uc4pRNVvmle1leQn1jcO5FkdWUyDyZniWFA50tud0s=
