language: java
script: echo Deploying
notifications:
  email:
    recipients:
    - alexander@district0x.io
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
    - district0x:53vhalUfg0MitsQwzjP5PWdd#travis-ci
services:
- docker
deploy:
- provider: script
  script: bash docker-push.sh
  on:
    branch: master
env:
  global:
  - secure: MT0NP379dJudrVF0yvggigh/dvXcLtD3TvEBC5amDxitL+w+rWwBvUqkV1Qwin7OxprObDE/eu9+bnhzrqkd3p4ZKm8Z+j+yj+C3RKoHNXguqR9d9qMITM6fbiBsoi+4KiLbksv9Vn7/XTpnYudszviHVjRb1H9cuCa9l3Pe0mWk4d5uNAFy6ZLq6iF1KrLWTO5H31eKjr4AREe5PdCRsQPC+NK4g8ZiPzk3JUaZAaI9D0ZfM1k7lC1qtMBX8AZ5OWjN3er4N60iMGGaimbREO+ovTZzJnCB/xunbyQC0DD5HU6vqQWfrj2K7f96jM1rtes21X7IW2WQLZmPsgvW7CeU2RFfzn4lyiVrTbuKRivEW3ahBOoxFT5msnWL0Zu1GN5Hv4cKC1j+fQOEraB820QOMedKmAdGUk72EVWvd/rXtmjf6HYg7inyMalTFHvBaPQcanbnRd0RCBM2YkQ9diwIeSLmnynb6nVLAaWu/omXEDZvZCUsfF1Radri7YGfgOuLDwb0OEKsoAdoInn3ZFnQOOBTZW2hVTkRWsj5hU5pcpxqqnb7jTs8UQwwOGXPHiQrfHpkmdgXBxuZ3U7GKid9EDBrB2FYESl414eKSvG24IQywoXZCei092ScMxPTQHK3Zi7ME84v4o3SWYBOzyZTpfzFN4CCPBdougZIs48=
  - secure: p1CoD2OkRVvGF3QRFiv4YELTgiMROo2SM+2FJwGqho4hjPdPPMNy4ABaEmoXmT4QmfLdPSP4yyDN8kEO9ZecLNva2XCWJmUxw5KosRboVKCDG7kGnsjGmSM7aV95RElSdyLkic8lncCTg7fNUqMH17abbEpTPpsFj2vwrV1irrjaTuJMhDYp2BSfIvMvNpPsNE4kI+jxEJ5O5kUnDxM+6vG0PPeuR5BS9+MbcKVuB3O9p9RdAY+yf/ClpVy0wAfG4ixFjlkOwreAj5aDHsmYJdzZcfWvHuzYQD4mHIsfLuwK+LHiYgHPD7LFYU4iGYqCTCC/lN4PDKZyA94pG1IwkgHyxArxPpQWDyJqlcQc1VrecAJe5NLIdtyBNOXubE8qeEKobDd3N9gHF3tZ0JTQZXu7Huhz0N4c0FuoiZB48J2sh0Aa/Bf+kkip9Wwew7g6XqQhPyQrcV9aBOe2U8N1obpaN5PHyH+3jc1fLjc2iKLTSgCx91rd3OoKWmY8e6ROzqSt3aOauF9QZUVsR6N+ZSbXCX5QMKi248jwUKklmWc7qEsuTylf0yyXMQnR8AAU6RKJ2b+iYQAyU1/sSJKlZRCZ0hCZfLyxAmj3jf/Url+sJ1SRbMbHwcDvWMoO03GLIy997iRDaexTlrUgXRxlopHhU6D9xkgMsXWsQRs48Lg=
